version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - psy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'Thinh@123'
      MYSQL_DATABASE: 'psy'
    ports:
      - "3306:3306"
    networks:
      - psy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/psy'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'Thinh@123'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - psy-network

networks:
  psy-network:
